---
 - name: Install dependencies packages of ruby
   become: yes
   yum:
     name: "{{ packages }}"
     state: present
     lock_timeout: 180
   vars:
     packages:
       - git-core
       - gcc
       - gcc-c++
       - gdbm-devel
       - libffi-devel
       - libselinux-python
       - libyaml-devel
       - mysql
       - mysql-devel
       - ncurses-devel
       - openssl-devel
       - sqlite-devel
       - readline-devel
       - zlib-devel
 - name: Install rbenv
   git:
     repo: https://github.com/sstephenson/rbenv.git
     dest: /usr/local/rbenv 
 
 - name: Edit bashrc
   template:
     src: roles/ruby/templates/rbenv_system.sh.j2
     dest: /etc/profile.d/rbenv.sh
     owner: ec2-user
     group: ec2-user

 - name: Install ruby-build
   git:
     repo: https://github.com/sstephenson/ruby-build.git
     dest: /usr/local/rbenv/plugins/ruby-build

 - name: Copy .gemrc to ~/.gemrc to Avoid to Install rb-docs
   become: yes
   copy: 
     src: .gemrc
     dest: ~/.gemrc

 - name: Install ruby
   shell: bash -lc "rbenv install -s 2.6.1"

 - name: Enable ruby installed version
   shell: bash -lc "rbenv global 2.6.1 && rbenv rehash"

 - name: Install bundler and so on
   shell: bash -lc "gem install {{ item }}"
   with_items:
     - rbenv-rehash
     - bundler -v 2.0.1
     - rails -v 6.0.0
